### ISSUE TITLE
accuracy metric

### ISSUE THREAD

**Issue by lengjia** [PengZhenghao/AXNet#1]
Hello! @PengZhenghao 
I have cloned the AXNet and followed the paper "AXNet: approximate computing using an end-to-end trainable neural network". nice work!
but I have some question:
for the "inversek2j" application, the parameters used in the AXNet program [https://github.com/PengZhenghao/AXNet/blob/master/example.ipynb](url)  is `bench_mark = 'inversek2j'
total_iteration = 50000
total_LR =  1e-4
error_bound = 0.1`, but the error bound in your paper is `error _bound=0.01` with corresponding prediction accuracy near 80%. 
when I follow the idea, and set the `error _bound=0.01`, the accuracy is about 67%. I wanna find the reason 
that I going wrong. Thanks!

**Comment by pengzhenghao** [comment]
I look up our experiment log and find that the result 80% came from the setting "error_bound=0.1; approximator=[2, 6, 2]; predictor=[2, 4, 8]". And unfortunately we haven't set the random seed at that time so it's probably hard to exactly retrieve the same result. Apologize to you for the mistake in paper and our rough implementation!
